import express from 'express';
import authRoutes from './Routes/authRoutes.js';
import productRoutes from './Routes/productRoutes.js';
import cartOrderRoutes from './Routes/cartOrderRoutes.js';
import userRoutes from './Routes/userRoutes.js';
import extraRoutes from './Routes/extraRoutes.js';
import mediaRoutes from './Routes/mediaRoutes.js';
import adminRoutes from './Routes/adminRoutes.js';
import merchantRoutes from './Routes/merchantRoutes.js';
import momoRoutes from './Routes/momoRoutes.js';
import inventoryRoutes from './Routes/inventoryRoutes.js';
import fulfillmentRoutes from './Routes/fulfillmentRoutes.js';
import analyticsRoutes from './Routes/analyticsRoutes.js';
import marketingRoutes from './Routes/marketingRoutes.js';
import promoCampaignRoutes from './Routes/promoCampaignRoutes.js';
import shipmentRoutes from './Routes/shipmentRoutes.js';
import merchantAnalyticsRoutes from './Routes/merchantAnalyticsRoutes.js';
import platformControlsRoutes from './Routes/platformControlsRoutes.js';
import billingRoutes from './Routes/billingRoutes.js';
import platformOperationsRoutes from './Routes/platformOperationsRoutes.js';
import reconciliationRoutes from './Routes/reconciliationRoutes.js';
import reportingRoutes from './Routes/reportingRoutes.js';
import walletRoutes from './Routes/walletRoutes.js';
import storeFollowRoutes from './Routes/storeFollowRoutes.js';
import merchantSettlementRoutes from './Routes/merchantSettlementRoutes.js';
import merchantProfileRoutes from './Routes/merchantProfileRoutes.js';
import merchantSettlementHistoryRoutes from './Routes/merchantSettlementHistoryRoutes.js';
import merchantOrderDetailsRoutes from './Routes/merchantOrderDetailsRoutes.js';
import adminUserRoutes from './Routes/adminUserRoutes.js';
import adminOperationsRoutes from './Routes/adminOperationsRoutes.js';
import merchantAdminRoutes from './Routes/merchantAdminRoutes.js';
import adminPaymentRoutes from './Routes/adminPaymentRoutes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/', cartOrderRoutes);
router.use('/users', userRoutes);
router.use('/', extraRoutes);
router.use('/media', mediaRoutes);
router.use('/admin', adminRoutes);
router.use('/merchant', merchantRoutes);
router.use('/merchant/profile', merchantProfileRoutes);
router.use('/merchant/settlements', merchantSettlementRoutes);
router.use('/merchant/settlement-history', merchantSettlementHistoryRoutes);
router.use('/merchant/orders/details', merchantOrderDetailsRoutes);
router.use('/admin/merchants', merchantAdminRoutes);
router.use('/admin/users', adminUserRoutes);
router.use('/admin/operations', adminOperationsRoutes);
router.use('/admin/payments', adminPaymentRoutes);
router.use('/momo', momoRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/fulfillment', fulfillmentRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/marketing', marketingRoutes);
router.use('/promo', promoCampaignRoutes);
router.use('/shipping', shipmentRoutes);
router.use('/merchant-analytics', merchantAnalyticsRoutes);
router.use('/platform', platformControlsRoutes);
router.use('/billing', billingRoutes);
router.use('/operations', platformOperationsRoutes);
router.use('/reconciliation', reconciliationRoutes);
router.use('/reporting', reportingRoutes);
router.use('/wallet', walletRoutes);
router.use('/stores/follows', storeFollowRoutes);

export default router;
